name: ubuntu-latest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install_dependencies
      run: sudo apt-get install libcunit1-dev clang

    - name: make
      run: make clean all

    - name: clang_sanitize_address
      env:
        CC: clang
        CFLAGS: -g -O0 -fsanitize=address
        LDFLAGS: -g -fsanitize=address
      run: make clean test

    - name: clang_sanitize_address_device_errors
      env:
        CC: clang
        CFLAGS: -g -O0 -fsanitize=address -DUSE_DEVICE_DEPENDENT_ERROR_INFORMATION=0
        LDFLAGS: -g -fsanitize=address
      run: make clean test
      
    - name: clang_sanitize_address_nomalloc
      env:
        CC: clang
        CFLAGS: -g -O0 -fsanitize=address -DUSE_MEMORY_ALLOCATION_FREE=0
        LDFLAGS: -g -fsanitize=address
      run: make clean test

    - name: coverage
      env:
        CFLAGS: -fprofile-arcs -ftest-coverage
        LDFLAGS: -lgcov
      run: make clean all test
    
    - name: lcov_capture
      run: lcov --capture --directory . --output-file coverage.info

    - name: lcov_cleanup
      run: lcov --remove coverage.info 'test/*' --output-file coverage.info
   
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: libscpi/
        path-to-lcov: coverage.info
